= Spring Auth API Documentation

== Auth Endpoints

=== Login
This is an example output for the `POST /auth/login` endpoint.

.request
include::auth/login/http-request.adoc[]

.response
include::auth/login/http-response.adoc[]

It gives informations about the authenticated user along with a JWT token.

==== Error Response - 400
These are example outputs for the `POST /auth/login` endpoint for bad request.

==== Missing Login
This is an example output when the login field is missing in the request.

.request
include::auth/login-missing-login/http-request.adoc[]

.response
include::auth/login-missing-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the login field is required.

==== Missing Password
This is an example output when the password field is missing in the request.

.request
include::auth/login-missing-password/http-request.adoc[]

.response
include::auth/login-missing-password/http-response.adoc[]

It returns a 400 Bad Request error indicating that the password field is required.

=== Register
This is an example output for the `POST /auth/register` endpoint.

.request
include::auth/register/http-request.adoc[]

.response
include::auth/register/http-response.adoc[]

It registers a new user and gives informations about the created user along with a JWT token.

=== Refresh
This is an example output for the `GET /auth/refresh` endpoint.

.request
include::auth/refresh/http-request.adoc[]

.response
include::auth/refresh/http-response.adoc[]

It refreshes the JWT token for the authenticated user.

== User Endpoints

=== Get Authenticated User
This is an example output for the `GET /users/me` endpoint.

.request
include::users/me/http-request.adoc[]

.response
include::users/me/http-response.adoc[]

It gives informations about the authenticated user.

=== Get All Users
This is an example output for the `GET /users/all` endpoint.

.request
include::users/all/http-request.adoc[]

.response
include::users/all/http-response.adoc[]

It gives informations about all users.

=== Promote User to Manager
This is an example output for the `PUT /users/{userId}/promote-manager` endpoint.

.request
include::users/promote-manager/http-request.adoc[]

.response
include::users/promote-manager/http-response.adoc[]

It promotes a user to the "MANAGER" role.

=== Revoke Manager to User
This is an example output for the `PUT /users/{userId}/revoke-manager` endpoint.

.request
include::users/revoke-manager/http-request.adoc[]

.response
include::users/revoke-manager/http-response.adoc[]

It revokes a manager to "USER" role.

=== Promote to Admin
This is an example output for the `PUT /users/{userId}/promote-admin` endpoint.

.request
include::users/promote-admin/http-request.adoc[]

.response
include::users/promote-admin/http-response.adoc[]

It promotes a user or manager to "ADMIN" role.

=== Revoke Admin to User
This is an example output for the `PUT /users/{userId}/revoke-admin` endpoint.

.request
include::users/revoke-admin/http-request.adoc[]

.response
include::users/revoke-admin/http-response.adoc[]

It revokes a admin to "USER" role.

=== Downgrade Admin to Manager
This is an example output for the `PUT /users/{userId}/downgrade-admin` endpoint.

.request
include::users/downgrade-admin/http-request.adoc[]

.response
include::users/downgrade-admin/http-response.adoc[]

It downgrades a admin to "MANAGER" role.

=== Delete User
This is an example output for the `DELETE /users/{userId}` endpoint.

.request
include::users/delete/http-request.adoc[]

.response
include::users/delete/http-response.adoc[]

It deletes a user.

