= Spring Auth API Documentation

== User Endpoints

=== Get Authenticated User
This is an example output for the `GET /users/me` endpoint.

.request
include::users/me/http-request.adoc[]

.response
include::users/me/http-response.adoc[]

It gives informations about the authenticated user.

==== 401 Unauthorized
This is an example output for the `GET /users/me` endpoint when the user is not authenticated.

.request
include::users/me/401/http-request.adoc[]

.response
include::users/me/401/http-response.adoc[]

It gives a 401 Unauthorized response when the user is not authenticated.

=== Get All Users
This is an example output for the `GET /users/all` endpoint.

.request
include::users/all/http-request.adoc[]

.response
include::users/all/http-response.adoc[]

It gives informations about all users.

==== 401 Unauthorized
This is an example output for the `GET /users/all` endpoint when the user is not authenticated.

.request
include::users/all/401/http-request.adoc[]

.response
include::users/all/401/http-response.adoc[]

It gives a 401 Unauthorized response when the user is not authenticated.

=== Promote User to Manager
This is an example output for the `PUT /users/{userId}/promote-manager` endpoint.

.request
include::users/promote-manager/http-request.adoc[]

.response
include::users/promote-manager/http-response.adoc[]

It promotes a user to the "MANAGER" role.

=== Revoke Manager to User
This is an example output for the `PUT /users/{userId}/revoke-manager` endpoint.

.request
include::users/revoke-manager/http-request.adoc[]

.response
include::users/revoke-manager/http-response.adoc[]

It revokes a manager to "USER" role.

=== Promote to Admin
This is an example output for the `PUT /users/{userId}/promote-admin` endpoint.

.request
include::users/promote-admin/http-request.adoc[]

.response
include::users/promote-admin/http-response.adoc[]

It promotes a user or manager to "ADMIN" role.

=== Revoke Admin to User
This is an example output for the `PUT /users/{userId}/revoke-admin` endpoint.

.request
include::users/revoke-admin/http-request.adoc[]

.response
include::users/revoke-admin/http-response.adoc[]

It revokes a admin to "USER" role.

=== Downgrade Admin to Manager
This is an example output for the `PUT /users/{userId}/downgrade-admin` endpoint.

.request
include::users/downgrade-admin/http-request.adoc[]

.response
include::users/downgrade-admin/http-response.adoc[]

It downgrades a admin to "MANAGER" role.

=== Delete User
This is an example output for the `DELETE /users/{userId}` endpoint.

.request
include::users/delete/http-request.adoc[]

.response
include::users/delete/http-response.adoc[]

It deletes a user.

