= Spring Auth API Documentation

== Auth Endpoints

=== Login
This is an example output for the `POST /auth/login` endpoint.

.request
include::auth/login/http-request.adoc[]

.response
include::auth/login/http-response.adoc[]

It gives informations about the authenticated user along with a JWT token.

==== Error Response - 400
These are example outputs for the `POST /auth/login` endpoint for bad request.

===== Missing Login
This is an example output when the login field is missing in the request.

.request
include::auth/login-missing-login/http-request.adoc[]

.response
include::auth/login-missing-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the login field is required.

===== Missing Password
This is an example output when the password field is missing in the request.

.request
include::auth/login-missing-password/http-request.adoc[]

.response
include::auth/login-missing-password/http-response.adoc[]

It returns a 400 Bad Request error indicating that the password field is required.

===== Invalid Email Format
This is an example output when the email format is invalid in the request.

.request
include::auth/login-invalid-email-format/http-request.adoc[]

.response
include::auth/login-invalid-email-format/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

===== Empty Body
This is an example output when the request body is empty.

.request
include::auth/login-empty-body/http-request.adoc[]

.response
include::auth/login-empty-body/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is missing.

===== Malformed JSON
This is an example output when the request body contains malformed JSON.

.request
include::auth/login-malformed-json/http-request.adoc[]

.response
include::auth/login-malformed-json/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is malformed.

===== SQL Injection Attempt Login
This is an example output when the login field contains a SQL injection attempt.

.request
include::auth/login-sql-injection-attempt-login/http-request.adoc[]

.response
include::auth/login-sql-injection-attempt-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

==== Error Response - 401
These are example outputs for the `POST /auth/login` endpoint for unauthorized access.

===== SQL Injection Attempt Password
This is an example output when the password field contains a SQL injection attempt.

.request
include::auth/login-sql-injection-attempt-password/http-request.adoc[]

.response
include::auth/login-sql-injection-attempt-password/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the credentials are invalid.

===== Wrong Password
This is an example output when the password provided is incorrect.

.request
include::auth/login-wrong-password/http-request.adoc[]

.response
include::auth/login-wrong-password/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the password is invalid.

===== Non-Existent User
This is an example output when the user does not exist.

.request
include::auth/login-non-existent-user/http-request.adoc[]

.response
include::auth/login-non-existent-user/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the credentials are invalid.

==== Error Response - 415
These are example outputs for the `POST /auth/login` endpoint for unsupported media types.

===== Unsupported Media Type
This is an example output when the media type of the request is unsupported.

.request
include::auth/login-wrong-media-type/http-request.adoc[]

.response
include::auth/login-wrong-media-type/http-response.adoc[]

It returns a 415 Unsupported Media Type error indicating that the media type is not supported.

=== Register
This is an example output for the `POST /auth/register` endpoint.

.request
include::auth/register/http-request.adoc[]

.response
include::auth/register/http-response.adoc[]

It registers a new user and gives informations about the created user along with a JWT token.

==== Error Response - 400
These are example outputs for the `POST /auth/register` endpoint for bad request.

===== Missing First Name
This is an example output when the first name field is missing in the request.

.request
include::auth/register-missing-first-name/http-request.adoc[]

.response
include::auth/register-missing-first-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the first name field is required.

===== Missing Last Name
This is an example output when the last name field is missing in the request.

.request
include::auth/register-missing-last-name/http-request.adoc[]

.response
include::auth/register-missing-last-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the last name field is required.

===== Missing Login
This is an example output when the login field is missing in the request.

.request
include::auth/register-missing-login/http-request.adoc[]

.response
include::auth/register-missing-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the login field is required.

===== Missing Password
This is an example output when the password field is missing in the request.

.request
include::auth/register-missing-password/http-request.adoc[]

.response
include::auth/register-missing-password/http-response.adoc[]

It returns a 400 Bad Request error indicating that the password field is required.

===== Invalid Email Format
This is an example output when the email format is invalid in the request.

.request
include::auth/register-invalid-email-format/http-request.adoc[]

.response
include::auth/register-invalid-email-format/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

===== Empty Body
This is an example output when the request body is empty.

.request
include::auth/register-empty-body/http-request.adoc[]

.response
include::auth/register-empty-body/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is missing.

===== Malformed JSON
This is an example output when the request body contains malformed JSON.

.request
include::auth/register-malformed-json/http-request.adoc[]

.response
include::auth/register-malformed-json/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is malformed.

===== SQL Injection Attempt First Name
This is an example output when the first name field contains a SQL injection attempt.

.request
include::auth/register-sql-injection-attempt-first-name/http-request.adoc[]

.response
include::auth/register-sql-injection-attempt-first-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the first name field is invalid.

===== SQL Injection Attempt Last Name
This is an example output when the last name field contains a SQL injection attempt.

.request
include::auth/register-sql-injection-attempt-last-name/http-request.adoc[]

.response
include::auth/register-sql-injection-attempt-last-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the last name field is invalid.

===== SQL Injection Attempt Login
This is an example output when the login field contains a SQL injection attempt.

.request
include::auth/register-sql-injection-attempt-login/http-request.adoc[]

.response
include::auth/register-sql-injection-attempt-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

=== Refresh
This is an example output for the `GET /auth/refresh` endpoint.

.request
include::auth/refresh/http-request.adoc[]

.response
include::auth/refresh/http-response.adoc[]

It refreshes the JWT token for the authenticated user.

== User Endpoints

=== Get Authenticated User
This is an example output for the `GET /users/me` endpoint.

.request
include::users/me/http-request.adoc[]

.response
include::users/me/http-response.adoc[]

It gives informations about the authenticated user.

=== Get All Users
This is an example output for the `GET /users/all` endpoint.

.request
include::users/all/http-request.adoc[]

.response
include::users/all/http-response.adoc[]

It gives informations about all users.

=== Promote User to Manager
This is an example output for the `PUT /users/{userId}/promote-manager` endpoint.

.request
include::users/promote-manager/http-request.adoc[]

.response
include::users/promote-manager/http-response.adoc[]

It promotes a user to the "MANAGER" role.

=== Revoke Manager to User
This is an example output for the `PUT /users/{userId}/revoke-manager` endpoint.

.request
include::users/revoke-manager/http-request.adoc[]

.response
include::users/revoke-manager/http-response.adoc[]

It revokes a manager to "USER" role.

=== Promote to Admin
This is an example output for the `PUT /users/{userId}/promote-admin` endpoint.

.request
include::users/promote-admin/http-request.adoc[]

.response
include::users/promote-admin/http-response.adoc[]

It promotes a user or manager to "ADMIN" role.

=== Revoke Admin to User
This is an example output for the `PUT /users/{userId}/revoke-admin` endpoint.

.request
include::users/revoke-admin/http-request.adoc[]

.response
include::users/revoke-admin/http-response.adoc[]

It revokes a admin to "USER" role.

=== Downgrade Admin to Manager
This is an example output for the `PUT /users/{userId}/downgrade-admin` endpoint.

.request
include::users/downgrade-admin/http-request.adoc[]

.response
include::users/downgrade-admin/http-response.adoc[]

It downgrades a admin to "MANAGER" role.

=== Delete User
This is an example output for the `DELETE /users/{userId}` endpoint.

.request
include::users/delete/http-request.adoc[]

.response
include::users/delete/http-response.adoc[]

It deletes a user.

