= Spring Auth API Documentation
:toc: right
:toclevels: 4 
:toc-title: Table of Contents

== 1 Auth Endpoints

=== 1.1 Login
This is an example output for the `POST /auth/login` endpoint.

.request
include::auth/login/http-request.adoc[]

.response
include::auth/login/http-response.adoc[]

It gives informations about the authenticated user along with a JWT token.

==== 1.1.1 Error Response - 400 - Bad Request
These are example outputs for the `POST /auth/login` endpoint for bad request.

===== 1.1.1.1 Missing Login
This is an example output when the login field is missing in the request.

.request
include::auth/login-missing-login/http-request.adoc[]

.response
include::auth/login-missing-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the login field is required.

===== 1.1.1.2 Missing Password
This is an example output when the password field is missing in the request.

.request
include::auth/login-missing-password/http-request.adoc[]

.response
include::auth/login-missing-password/http-response.adoc[]

It returns a 400 Bad Request error indicating that the password field is required.

===== 1.1.1.3 Invalid Email Format
This is an example output when the email format is invalid in the request.

.request
include::auth/login-invalid-email-format/http-request.adoc[]

.response
include::auth/login-invalid-email-format/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

===== 1.1.1.4 Empty Body
This is an example output when the request body is empty.

.request
include::auth/login-empty-body/http-request.adoc[]

.response
include::auth/login-empty-body/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is missing.

===== 1.1.1.5 Malformed JSON
This is an example output when the request body contains malformed JSON.

.request
include::auth/login-malformed-json/http-request.adoc[]

.response
include::auth/login-malformed-json/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is malformed.

===== 1.1.1.6 SQL Injection Attempt Login
This is an example output when the login field contains a SQL injection attempt.

.request
include::auth/login-sql-injection-attempt-login/http-request.adoc[]

.response
include::auth/login-sql-injection-attempt-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

==== 1.1.2 Error Response - 401 - Unauthorized
These are example outputs for the `POST /auth/login` endpoint for unauthorized access.

===== 1.1.2.1 Wrong Password
This is an example output when the password provided is incorrect.

.request
include::auth/login-wrong-password/http-request.adoc[]

.response
include::auth/login-wrong-password/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the password is invalid.

===== 1.1.2.2 Non-Existent User
This is an example output when the user does not exist.

.request
include::auth/login-non-existent-user/http-request.adoc[]

.response
include::auth/login-non-existent-user/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the credentials are invalid.

==== 1.1.3 Error Response - 415 - Unsupported Media Type
These are example outputs for the `POST /auth/login` endpoint for unsupported media types.

===== 1.1.3.1 Unsupported Media Type
This is an example output when the media type of the request is unsupported.

.request
include::auth/login-wrong-media-type/http-request.adoc[]

.response
include::auth/login-wrong-media-type/http-response.adoc[]

It returns a 415 Unsupported Media Type error indicating that the media type is not supported.

=== 1.2 Register
This is an example output for the `POST /auth/register` endpoint.

.request
include::auth/register/http-request.adoc[]

.response
include::auth/register/http-response.adoc[]

It registers a new user and gives informations about the created user along with a JWT token.

==== 1.2.1 Error Response - 400 - Bad Request
These are example outputs for the `POST /auth/register` endpoint for bad request.

===== 1.2.1.1 Missing First Name
This is an example output when the first name field is missing in the request.

.request
include::auth/register-missing-first-name/http-request.adoc[]

.response
include::auth/register-missing-first-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the first name field is required.

===== 1.2.1.2 Missing Last Name
This is an example output when the last name field is missing in the request.

.request
include::auth/register-missing-last-name/http-request.adoc[]

.response
include::auth/register-missing-last-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the last name field is required.

===== 1.2.1.3 Missing Login
This is an example output when the login field is missing in the request.

.request
include::auth/register-missing-login/http-request.adoc[]

.response
include::auth/register-missing-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the login field is required.

===== 1.2.1.4 Missing Password
This is an example output when the password field is missing in the request.

.request
include::auth/register-missing-password/http-request.adoc[]

.response
include::auth/register-missing-password/http-response.adoc[]

It returns a 400 Bad Request error indicating that the password field is required.

===== 1.2.1.5 Invalid Email Format
This is an example output when the email format is invalid in the request.

.request
include::auth/register-invalid-email-format/http-request.adoc[]

.response
include::auth/register-invalid-email-format/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

===== 1.2.1.6 Empty Body
This is an example output when the request body is empty.

.request
include::auth/register-empty-body/http-request.adoc[]

.response
include::auth/register-empty-body/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is missing.

===== 1.2.1.7 Malformed JSON
This is an example output when the request body contains malformed JSON.

.request
include::auth/register-malformed-json/http-request.adoc[]

.response
include::auth/register-malformed-json/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is malformed.

===== 1.2.1.8 SQL Injection Attempt First Name
This is an example output when the first name field contains a SQL injection attempt.

.request
include::auth/register-sql-injection-attempt-first-name/http-request.adoc[]

.response
include::auth/register-sql-injection-attempt-first-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the first name field is invalid.

===== 1.2.1.9 SQL Injection Attempt Last Name
This is an example output when the last name field contains a SQL injection attempt.

.request
include::auth/register-sql-injection-attempt-last-name/http-request.adoc[]

.response
include::auth/register-sql-injection-attempt-last-name/http-response.adoc[]

It returns a 400 Bad Request error indicating that the last name field is invalid.

===== 1.2.1.10 SQL Injection Attempt Login
This is an example output when the login field contains a SQL injection attempt.

.request
include::auth/register-sql-injection-attempt-login/http-request.adoc[]

.response
include::auth/register-sql-injection-attempt-login/http-response.adoc[]

It returns a 400 Bad Request error indicating that the email format is invalid.

==== 1.2.2 Error Response - 409 - Conflict
These are example outputs for the `POST /auth/register` endpoint for conflict errors.

===== 1.2.2.1 Duplicate Login
This is an example output when the login provided already exists.

.request
include::auth/register-duplicate-login/http-request.adoc[]

.response
include::auth/register-duplicate-login/http-response.adoc[]

It returns a 409 Conflict error indicating that the login already exists.

==== 1.2.3 Error Response - 415 - Unsupported Media Type
These are example outputs for the `POST /auth/register` endpoint for unsupported media types.

===== 1.2.3.1 Unsupported Media Type
This is an example output when the media type of the request is unsupported.

.request
include::auth/register-wrong-media-type/http-request.adoc[]

.response
include::auth/register-wrong-media-type/http-response.adoc[]

It returns a 415 Unsupported Media Type error indicating that the media type is not supported.

=== 1.3 Refresh
This is an example output for the `GET /auth/refresh` endpoint.

.request
include::auth/refresh/http-request.adoc[]

.response
include::auth/refresh/http-response.adoc[]

It refreshes the JWT token for the authenticated user.

=== 1.4 Update Password
This is an example output for the `PUT /auth/update-password` endpoint.

.request
include::auth/update-password/http-request.adoc[]

.response
include::auth/update-password/http-response.adoc[]

It sets a new password for the authenticated user.

==== 1.4.1 Error Response - 400 - Bad Request
These are example outputs for the `PUT /auth/update-password` endpoint for bad request.

===== 1.4.1.1 Missing Body
This is an example output when the request body is missing.

.request
include::auth/update-password-missing-body/http-request.adoc[]

.response
include::auth/update-password-missing-body/http-response.adoc[]

It returns a 400 Bad Request error indicating that the request body is missing.

==== 1.4.2 Error Response - 401 - Unauthorised
These are example outputs for the `PUT /auth/update-password` endpoint for unauthorized access.

===== 1.4.2.1 Missing Token
This is an example output when the request token is missing.

.request
include::auth/update-password-missing-token/http-request.adoc[]

.response
include::auth/update-password-missing-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

== 2 User Endpoints

=== 2.1 Get Authenticated User
This is an example output for the `GET /users/me` endpoint.

.request
include::users/me/http-request.adoc[]

.response
include::users/me/http-response.adoc[]

It gives informations about the authenticated user.

==== 2.1.1 Error Response - 401 - Unauthorized
These are example outputs for the `GET /users/me` endpoint for unauthorized access.

===== 2.1.1.1 Missing Authorization Header
This is an example output when the Authorization header is missing in the request.

.request
include::users/me-missing-authorization/http-request.adoc[]

.response
include::users/me-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.1.1.2 Malformed Token
This is an example output when the token provided is malformed.

.request
include::users/me-malformed-token/http-request.adoc[]

.response
include::users/me-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.

===== 2.1.1.3 Expired Token
This is an example output when the token provided is expired.

.request
include::users/me-expired-token/http-request.adoc[]

.response
include::users/me-expired-token/http-response.adoc[]

=== 2.2 Get All Users
This is an example output for the `GET /users/all` endpoint.

.request
include::users/all/http-request.adoc[]

.response
include::users/all/http-response.adoc[]

It gives informations about all users.

==== 2.2.1 Error Response - 401 - Unauthorized
These are example outputs for the `GET /users/all` endpoint for unauthorized access.

===== 2.2.1.1 Missing Authorization Header
This is an example output when the Authorization header is missing in the request.

.request
include::users/all-missing-authorization/http-request.adoc[]

.response
include::users/all-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.2.1.2 Malformed Token
This is an example output when the token provided is malformed.

.request
include::users/all-malformed-token/http-request.adoc[]

.response
include::users/all-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.

===== 2.2.1.3 Expired Token
This is an example output when the token provided is expired.

.request
include::users/all-expired-token/http-request.adoc[]

.response
include::users/all-expired-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token has expired.

=== 2.3 Promote User to Manager
This is an example output for the `PUT /users/{userId}/promote-manager` endpoint.

.request
include::users/promote-manager/http-request.adoc[]

.response
include::users/promote-manager/http-response.adoc[]

It promotes a user to the "MANAGER" role.

==== 2.3.1 Error Response - 401 - Unauthorized
These are example outputs for the `PUT /users/{userId}/promote-manager` endpoint for unauthorized access.

===== 2.3.1.1 Missing Authorization Header
This is an example output when the Authorization header is missing in the request.

.request
include::users/promote-manager-missing-authorization/http-request.adoc[]

.response
include::users/promote-manager-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.3.1.2 Malformed Token
This is an example output when the token provided is malformed.

.request
include::users/promote-manager-malformed-token/http-request.adoc[]

.response
include::users/promote-manager-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.

==== 2.3.2 Error Response - 403 - Forbidden
These are example outputs for the `PUT /users/{userId}/promote-manager` endpoint for forbidden access.

===== 2.3.2.1 Non-Admin User - Promote User to Manager
This is an example output when a non-admin user attempts to promote a user to manager.

.request
include::users/promote-manager-non-admin/http-request.adoc[]

.response
include::users/promote-manager-non-admin/http-response.adoc[]

It returns a 403 Forbidden error indicating that access is denied.

==== 2.3.3 Error Response - 404 - Not Found
These are example outputs for the `PUT /users/{userId}/promote-manager` endpoint for not found errors.

===== 2.3.3.1 User Not Found
This is an example output when the user to be promoted is not found.    

.request
include::users/promote-manager-user-not-found/http-request.adoc[]

.response
include::users/promote-manager-user-not-found/http-response.adoc[]

It returns a 404 Not Found error indicating that the user was not found.

==== 2.3.4 Error Response - 409 - Conflict
These are example outputs for the `PUT /users/{userId}/promote-manager` endpoint for conflict errors.

===== 2.3.4.1 User Already Manager
This is an example output when the user to be promoted is already a manager.

.request
include::users/promote-manager-user-already-manager/http-request.adoc[]

.response
include::users/promote-manager-user-already-manager/http-response.adoc[]

It returns a 409 Conflict error indicating that the user is already a manager.

===== 2.3.4.2 User Already Admin
This is an example output when the user to be promoted is already an admin.

.request
include::users/promote-manager-user-already-admin/http-request.adoc[]

.response
include::users/promote-manager-user-already-admin/http-response.adoc[]

It returns a 409 Conflict error indicating that the user is already an admin.

=== 2.4 Revoke Manager to User
This is an example output for the `PUT /users/{userId}/revoke-manager` endpoint.

.request
include::users/revoke-manager/http-request.adoc[]

.response
include::users/revoke-manager/http-response.adoc[]

It revokes a manager to "USER" role.

==== 2.4.1 Error Response - 401 - Unauthorized
These are example outputs for the `PUT /users/{userId}/revoke-manager` endpoint for unauthorized access.

===== 2.4.1.1 Missing Authorization Header
This is an example output when the Authorization header is missing in the request.

.request
include::users/revoke-manager-missing-authorization/http-request.adoc[]

.response
include::users/revoke-manager-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.4.1.2 Malformed Token
This is an example output when the token provided is malformed.

.request
include::users/revoke-manager-malformed-token/http-request.adoc[]

.response
include::users/revoke-manager-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.

==== 2.4.2 Error Response - 403 - Forbidden
These are example outputs for the `PUT /users/{userId}/revoke-manager` endpoint for forbidden access.

===== 2.4.2.1 Non-Admin User
This is an example output when a non-admin user tries to revoke a manager role.

.request
include::users/revoke-manager-non-admin/http-request.adoc[]

.response
include::users/revoke-manager-non-admin/http-response.adoc[]

It returns a 403 Forbidden error indicating that access is denied.

==== 2.4.3 Error Response - 404 - Not Found
These are example outputs for the `PUT /users/{userId}/revoke-manager` endpoint

===== 2.4.3.1 User Not Found
This is an example output when the user to be revoked is not found.

.request
include::users/revoke-manager-user-not-found/http-request.adoc[]

.response
include::users/revoke-manager-user-not-found/http-response.adoc[]

It returns a 404 Not Found error indicating that the user was not found.

=== 2.5 Promote to Admin
This is an example output for the `PUT /users/{userId}/promote-admin` endpoint.

.request
include::users/promote-admin/http-request.adoc[]

.response
include::users/promote-admin/http-response.adoc[]

It promotes a user or manager to "ADMIN" role.

==== 2.5.1 Error Response - 401 - Unauthorized
These are example outputs for the `PUT /users/{userId}/promote-admin` endpoint for unauthorized access.

===== 2.5.1.1 Missing Authorization Header
This is an example output when the Authorization header is missing in the request.
.request
include::users/promote-admin-missing-authorization/http-request.adoc[]

.response
include::users/promote-admin-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.5.1.2 Malformed Token
.request
include::users/promote-admin-malformed-token/http-request.adoc[]

.response
include::users/promote-admin-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.

==== 2.5.2 Error Response - 403 - Forbidden
These are example outputs for the `PUT /users/{userId}/promote-admin` endpoint for forbidden access.

===== 2.5.2.1 Non-Admin User
This is an example output when a non-admin user tries to promote a user to admin.
.request
include::users/promote-admin-non-admin/http-request.adoc[]

.response
include::users/promote-admin-non-admin/http-response.adoc[]

It returns a 403 Forbidden error indicating that access is denied.

==== 2.5.3 Error Response - 404 - Not Found
These are example outputs for the `PUT /users/{userId}/promote-admin` endpoint for not found errors.

===== 2.5.3.1 User Not Found
This is an example output when the user to be promoted is not found.
.request
include::users/promote-admin-user-not-found/http-request.adoc[]

.response
include::users/promote-admin-user-not-found/http-response.adoc[]

It returns a 404 Not Found error indicating that the user was not found.

==== 2.5.4 Error Response - 409 - Conflict
These are example outputs for the `PUT /users/{userId}/promote-admin` endpoint for conflict errors.

===== 2.5.4.1 User Already Admin
This is an example output when the user to be promoted is already an admin.
.request
include::users/promote-admin-user-already-admin/http-request.adoc[]

.response
include::users/promote-admin-user-already-admin/http-response.adoc[]

It returns a 409 Conflict error indicating that the user is already an admin.

=== 2.6 Revoke Admin to User
This is an example output for the `PUT /users/{userId}/revoke-admin` endpoint.

.request
include::users/revoke-admin/http-request.adoc[]

.response
include::users/revoke-admin/http-response.adoc[]

It revokes a admin to "USER" role.

==== 2.6.1 Error Response - 401 - Unauthorized
These are example outputs for the `PUT /users/{userId}/revoke-admin` endpoint for unauthorized access.

===== 2.6.1.1 Missing Authorization Header
.request
include::users/revoke-admin-missing-authorization/http-request.adoc[]

.response
include::users/revoke-admin-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.6.1.2 Malformed Token
This is an example output when the token provided is malformed.
.request
include::users/revoke-admin-malformed-token/http-request.adoc[]

.response
include::users/revoke-admin-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.

==== 2.6.2 Error Response - 403 - Forbidden
These are example outputs for the `PUT /users/{userId}/revoke-admin` endpoint for forbidden access.

===== 2.6.2.1 Non-Admin User
This is an example output when a non-admin user tries to revoke an admin role.

.request
include::users/revoke-admin-non-admin/http-request.adoc[]

.response
include::users/revoke-admin-non-admin/http-response.adoc[]

It returns a 403 Forbidden error indicating that access is denied.

==== 2.6.3 Error Response - 404 - Not Found
These are example outputs for the `PUT /users/{userId}/revoke-admin` endpoint for not found errors.

===== 2.6.3.1 User Not Found
This is an example output when the user to be revoked is not found.

.request
include::users/revoke-admin-user-not-found/http-request.adoc[]

.response
include::users/revoke-admin-user-not-found/http-response.adoc[]

It returns a 404 Not Found error indicating that the user was not found.

=== 2.7 Downgrade Admin to Manager
This is an example output for the `PUT /users/{userId}/downgrade-admin` endpoint.

.request
include::users/downgrade-admin/http-request.adoc[]

.response
include::users/downgrade-admin/http-response.adoc[]

It downgrades a admin to "MANAGER" role.

==== 2.7.1 Error Response - 401 - Unauthorized
These are example outputs for the `PUT /users/{userId}/downgrade-admin` endpoint for unauthorized access.

===== 2.7.1.1 Missing Authorization Header
This is an example output when the Authorization header is missing in the request.

.request
include::users/downgrade-admin-missing-authorization/http-request.adoc[]

.response
include::users/downgrade-admin-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.7.1.2 Malformed Token
This is an example output when the token provided is malformed.

.request
include::users/downgrade-admin-malformed-token/http-request.adoc[]

.response
include::users/downgrade-admin-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.

=== 2.8 Delete User
This is an example output for the `DELETE /users/{userId}` endpoint.

.request
include::users/delete/http-request.adoc[]

.response
include::users/delete/http-response.adoc[]

It deletes a user.

==== 2.8.1 Error Response - 401 - Unauthorized
These are example outputs for the `DELETE /users/{userId}` endpoint for unauthorized access.

===== 2.8.1.1 Missing Authorization Header
This is an example output when the Authorization header is missing in the request.

.request
include::users/delete-missing-authorization/http-request.adoc[]

.response
include::users/delete-missing-authorization/http-response.adoc[]

It returns a 401 Unauthorized error indicating that full authentication is required.

===== 2.8.1.2 Malformed Token
This is an example output when the token provided is malformed.

.request
include::users/delete-malformed-token/http-request.adoc[]

.response
include::users/delete-malformed-token/http-response.adoc[]

It returns a 401 Unauthorized error indicating that the token is invalid.